#!/bin/bash

. ns import se_sid se_x se_y se_wait

x=$se_x
y=$se_y
# a=$((se_x-1))
# b=$((se_y-1))
a=$x
b=$y

base_url=http://localhost:4444/session

read header1 <<EOF
Content-Type: application/json; charset=utf-8
EOF

sleep "$se_wait"

user_action_wait_milliseconds=$(echo "${se_wait}" | cut -d '.' -f1)
((user_action_wait_milliseconds*=1000))
read -r -d '' body <<EOF
{
    "actions": [
        {
            "type": "pointer",
            "id": "mouse",
            "parameters": {"pointerType": "mouse"},
            "actions":[
                { "type": "pause", "duration": ${user_action_wait_milliseconds} },
                {
                    "type":"pointerMove",
                    "origin": "viewport",
                    "x": $x,
                    "y": $y,
                    "duration": ${user_action_wait_milliseconds}
                },
                { "type": "pause", "duration": ${user_action_wait_milliseconds} },
                {
                    "type":"pointerDown",
                    "button": 0
                },
                { "type": "pause", "duration": ${user_action_wait_milliseconds} },
                {
                    "type":"pointerUp",
                    "button": 0
                },
                { "type": "pause", "duration": ${user_action_wait_milliseconds} }
            ]
        }
    ]
}
EOF
curl -s -H "$header1" -d "$body" ${base_url}/${se_sid}/actions 1>/dev/null 2>&1
sleep "$se_wait"

. ns export se_sid se_wait
