#!/bin/bash

. ns import se_sid se_eid se_keys se_wait

base_url=http://localhost:4444/session

user_action_wait_milliseconds=$(echo "${se_wait} * 1000" | bc | cut -d '.' -f1)

read header1 <<EOF
Content-Type: application/json; charset=utf-8
EOF

key_actions=
let n=${#se_keys}-1;
for i in $(seq 0 $n)
do
    ch=${se_keys:$i:1}
    read -r -d '' action <<EOF
{
    "type": "keyDown",
    "value": "$ch",
    "duration": ${user_action_wait_milliseconds}
},
{ "type": "pause", "duration": ${user_action_wait_milliseconds} },
{
    "type": "keyUp",
    "value": "$ch",
    "duration": ${user_action_wait_milliseconds}
}
EOF

    if [[ -z "$key_actions" ]]; then
        key_actions="${action}"
    else
        key_actions="${key_actions},${action}"
    fi
done

# echo "key actions: ${key_actions}"

read -r -d '' body <<EOF
{
    "actions": [
        {
            "type": "key",
            "id": "keyboard",
            "actions": [
                ${key_actions},
                { "type": "pause", "duration": ${user_action_wait_milliseconds} }
            ]
        }
    ]
}
EOF
# echo "$body"
curl -s -H "$header1" -d "$body" ${base_url}/${se_sid}/actions 1>/dev/null 2>&1
sleep "$se_wait"

. ns export se_sid se_wait
