#!/bin/bash

. ns import se_sid se_eid se_text se_x se_y se_x2 se_y2

x=$se_x
y=$se_y
x2=$se_x2
y2=$se_y2
echo "$x,$y,$x2,$y2"

base_url=http://localhost:4444/session

read header1 <<EOF
Content-Type: application/json; charset=utf-8
EOF

read -r -d '' body <<EOF
{
    "actions": [
        {
            "type": "pointer",
            "id": "mouse",
            "actions":[
                {
                    "type":"pointerMove",
                    "x": $x,
                    "y": $y,
                    "duration": 200
                },
                {
                    "type": "pause",
                    "duation": 200
                },
                {
                    "type":"pointerDown",
                    "button": 0,
                    "x": $x,
                    "y": $y
                },
                {
                    "type":"pointerMove",
                    "x": $x2,
                    "y": $y2
                },
                {
                    "type": "pause",
                    "duation": 200
                },
                {
                    "type":"pointerUp",
                    "button": 0,
                    "x": $x2,
                    "y": $y2,
                    "duration": 200
                },
                {
                    "type": "pause",
                    "duation": 200
                }
            ]
        }
    ]
}
EOF

curl -s -H "$header1" -d "$body" ${base_url}/${se_sid}/actions # 1>/dev/null 2>&1

. ns export se_sid
