#!/bin/bash

. ns import se_sid se_eid se_text

base_url=http://localhost:4444/session

read header1 <<EOF
Content-Type: application/json; charset=utf-8
EOF

read -r -d '' body <<EOF
{
    "text": "${se_text}"
}
EOF

curl -s -H "$header1" -d "$body" ${base_url}/${se_sid}/element/${se_eid}/value # 1>/dev/null 2>&1

. ns export se_sid
