#!/bin/bash

. ns import se_sid se_eid se_attr

base_url=http://localhost:4444/session

read header1 <<EOF
Content-Type: application/json; charset=utf-8
EOF

# read -r -d '' body <<EOF
# {
#     "value": "${se_attr}"
# }
# EOF

# get request:
get_response=$(curl -s -H "$header1" ${base_url}/${se_sid}/element/${se_eid}/attribute/${se_attr} 2>/dev/null)
se_val=$(echo "$get_response" | jq -r '.value')

. ns export se_sid se_val
