#!/bin/bash

. ns import se_sid se_xpath se_wait

base_url=http://localhost:4444/session

read header1 <<EOF
Content-Type: application/json; charset=utf-8
EOF

read -r -d '' body <<EOF
{
    "using": "xpath",
    "value": "${se_xpath}"
}
EOF
locate_response=$(curl -s -H "$header1" -d "$body" ${base_url}/${se_sid}/element 2>/dev/null)
# echo "$locate_response"
se_eid=
se_found=0
if [[ "${locate_response:0:17}" == '{"value":{"error"' ]]; then
    :
else
    se_found=1
    se_eid=$(echo "$locate_response" | jq -r '.value["element-6066-11e4-a52e-4f735466cecf"]')
fi
sleep "$se_wait"

. ns export se_found se_eid se_sid se_wait
