#!/bin/bash

. ns import se_url se_sid

base_url=http://localhost:4444/session

read header1 <<EOF
Content-Type: application/json; charset=utf-8
EOF

read -r -d '' body <<EOF
{
    "url": "$se_url"
}
EOF
curl -s -H "$header1" -d "$body" ${base_url}/${se_sid}/url 1>/dev/null 2>&1

. ns export se_sid
