#!/bin/bash

. ns import sel_sid ft_index ft_wait stp_svg
se_wait="$ft_wait"
# GO TO CURRENT CODE VERSION INDEX PAGE
se_sid="$sel_sid"
se_url="http://localhost:8000/${ft_index}"
. ns run se-session-url

# LOCATE TEXTAREA AND CLEAR IT
se_xpath="//textarea[@id='svgFullTextarea']"
. ns run se-element-xpath
. ns run se-element-clear

# SET (EMPTY OR RECT) SVG VALUE
se_xpath="//textarea[@id='svgFullTextarea']"
. ns run se-element-xpath
(
    # put svg text in post-start
    ft_start=
    ft_end=v0.1
    . ns run version-between
    if [[ $ft_found -eq 1 ]]; then
        read -r -d '' se_text <<EOF
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='750' height='750' viewBox='0,0,750,750'>${stp_svg}</svg>
EOF
        . ns run se-element-value
    fi
)


# force the on-change
se_xpath="//svg"
. ns run se-element-xpath
. ns run se-element-click

# LOCATE START BUTTON AND CLICK IT
se_xpath="//button[@id='buttonStart']"
. ns run se-element-xpath
. ns run se-element-click

(
    # put svg text in pre-start
    ft_start=v0.2
    ft_end=
    . ns run version-between
    if [[ $ft_found -eq 1 ]]; then
        se_xpath="//textarea[@id='svgFullTextarea']"
        . ns run se-element-xpath
        # echo "$se_found"
        read -r -d '' se_text <<EOF
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='750' height='750' viewBox='0,0,750,750'>${stp_svg}</svg>
EOF
        . ns run se-element-value # se-* scripts all end with: sleep $se_wait
    fi
)

# force the on-change
se_xpath="//*[name()='svg']"  # /*[name()='rect']"
. ns run se-element-xpath
. ns run se-element-click

# remove svg textarea focus (no-op clicks on rhs of pane, draw/selections on lhs):
se_x=1051
se_y=451
se_x2=1101
se_y2=501
. ns run se-actions-dragged-click

# select mode
se_keys="0"
. ns run se-actions-keys

. ns export sel_sid ft_index ft_wait
