#!/bin/bash

. ns import ft_index sel_sid

# TODO: pass in the ft_version to choose which kind of drawing to make (click-drag or two clicks)

# TEST ONE - TEST RECTANGLE CAN BE SELECTED

. ns run setup

se_sid="$sel_sid"

# rect mode
se_keys="3"
. ns run se-actions-keys
sleep 1

# TODO: draw rect in previous versions
# . ns run se-actions-diagonal-clicks

# draw rect
se_x=771
se_y=171
se_x2=971
se_y2=371
. ns run se-actions-dragged-click

# select mode
se_keys="0"
. ns run se-actions-keys
sleep 1


# act
se_x=855
se_y=275
. ns run se-actions-click
sleep 1

se_xpath="//*[name()='rect']"
. ns run se-element-xpath
se_attr="stroke"
. ns run se-element-attribute

# TODO: change to a version assert (once implemented)
if [[ "$se_val" == "#CAFFB5" ]]; then
    echo PASS
else
    echo FAIL
fi

. ns export ft_index sel_sid
