#!/bin/bash

. ns import ft_harness ft_index sel_sid ft_wait

se_wait=$ft_wait

# TEST ONE - TEST RECTANGLE CAN BE SELECTED
test="RECTANGLE CAN BE SELECTED"

# must use single quotes (until setup script is updated)
read -r -d '' stp_svg <<EOF
<rect rx='0' ry='0' x='24' y='86' width='197' height='197' stroke='black' fill='transparent' stroke-width='1'/>
EOF
. ns run setup

se_sid="$sel_sid"

# select mode
se_keys="0"
. ns run se-actions-keys
sleep "$se_wait"


# act
se_x=855
se_y=275
. ns run se-actions-click

se_xpath="//*[name()='rect']"
. ns run se-element-xpath
se_attr="stroke"
. ns run se-element-attribute

# TEST ONE - FEATURED IN VERSION(S) ASSERT
ft_start=
ft_end=
ft_assert=0
# echo "val: $se_val"
if [[ "$se_val" == "#CAFFB5" ]]; then
    ft_assert=1
fi
. ns run version-assert
dots=".............................................."
test="${ft_sut_v} TEST (${ft_status}) ${test}"
dotl=${#dots}; testl=${#test}; ((dotl-=testl)); dots="${dots:0:$dotl}"; test="${test}.${dots}."
if [[ $ft_assert -eq 1 ]]; then
    echo "${test}...PASS"
else
    echo "${test}...FAIL"
fi
. ns export ft_harness ft_index sel_sid ft_wait
