#!/bin/bash

. ns import ft_harness ft_index sel_sid ft_wait

se_wait=$ft_wait

# TEST TWO - TEST RECTANGLE CAN BE DRAWN
test="RECTANGLE CAN BE DRAWN"

stp_svg=
. ns run setup

se_sid="$sel_sid"

# rect mode
se_keys="3"
. ns run se-actions-keys
sleep "$se_wait"

# draw rect
se_x=771
se_y=171
se_x2=971
se_y2=371
(
    ft_start=
    ft_end=v0.0
    . ns run version-between
    if [[ $ft_found -gt 0 ]]; then
        # two-click draw
        ft_start=v0.0
        ft_end=v0.0
        . ns run version-between
        if [[ $ft_found -gt 0 ]]; then
            # only click-draw rect if version is >= v0.0
            # as initial (devbox) version only supports selection
            . ns run se-actions-diagonal-clicks
        fi
    else
        # click-and-drag draw
        . ns run se-actions-dragged-click
    fi
)

se_xpath="//*[name()='rect']"
. ns run se-element-xpath

# VERSION(S) ASSERT
ft_assert=$se_found
ft_start=v0.0
ft_end=
. ns run version-assert
dots=".............................................."
test="${ft_sut_v} TEST (${ft_status}) ${test}"
dotl=${#dots}; testl=${#test}; ((dotl-=testl)); dots="${dots:0:$dotl}"; test="${test}.${dots}."
if [[ $ft_assert -eq 1 ]]; then
    echo "${test}...PASS"
else
    echo "${test}...FAIL"
fi
. ns export ft_harness ft_index sel_sid ft_wait
