#!/bin/bash

. ns import ft_index sel_sid

. ns run setup


se_sid="$sel_sid"

# rect mode
se_keys="3"
. ns run se-actions-keys
sleep 1

# draw rect
# . ns run se-actions-diagonal-clicks
se_x=771
se_y=171
se_x2=se_x; ((se_x2+=400));
se_y2=se_y; ((se_y2+=400));
. ns run se-actions-dragged-click

# todo: still need to add in the selection code and test
echo FAIL

. ns export ft_index sel_sid
